services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: loguser
      POSTGRES_PASSWORD: logpass
      POSTGRES_DB: logs
    ports: ["5433:5432"]   # host 5433: evita conflito com um Postgres nativo já usando 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U loguser -d logs"]
      interval: 5s
      retries: 5

  elasticsearch:
    image: elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m   # limita RAM no dev local
    ports: ["9200:9200"]
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9200/_cluster/health"]
      interval: 10s
      retries: 10

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  api:
    build: .
    depends_on:
      postgres: { condition: service_healthy }
      elasticsearch: { condition: service_healthy }
      redis: { condition: service_started }
    env_file: .env
    ports: ["3000:3000"]

volumes:
  pgdata:
  esdata: